#
#  Rules for setting up and resetting data
#
#-------------------------------------------------------------------------------

all:	reset

#-------------------------------------------------------------------------------

setup:
	cp ../Model/Globals.master              Globals.dat
	cp ../Model/Profiles.master             Profiles.dat
	cp ../Model/Sequence.master             Sequence.dat
	cp ../Model/SerialNo.master             SerialNo.dat
	cp ../Model/Indexed.master              Indexed.dat
	cp ../Model/Hashed.master               Hashed.dat
	cp ../Model/Keyed.master                Keyed.dat
	cp ../Model/KeyedSequence.master        KeyedSequence.dat
	cp ../Model/Store.master                Store.dat
	cp ../Model/Test.master                 Test.dat

#-------------------------------------------------------------------------------

reset:
	cp ../Model/Globals.master              Globals.dat
	cp ../Model/Profiles.master             Profiles.dat
	cp ../Model/Sequence.master             Sequence.dat
	cp ../Model/SerialNo.master             SerialNo.dat
	cp ../Model/Indexed.master              Indexed.dat
	cp ../Model/Hashed.master               Hashed.dat
	cp ../Model/Keyed.master                Keyed.dat
	cp ../Model/KeyedSequence.master        KeyedSequence.dat
	cp ../Model/Store.master                Store.dat
	cp ../Model/Test.master                 Test.dat

#-------------------------------------------------------------------------------

clean:
	-rm tmp/*2011* tmp/*.used tmp/*.stored

#-------------------------------------------------------------------------------

